-- 自动生成的数据库表结构
-- 所有字段使用TEXT类型，保留API原始字段名


-- BINANCE 永续合约表
CREATE TABLE IF NOT EXISTS binance_perpetual (
    id SERIAL PRIMARY KEY,
    baseAsset TEXT,
    baseAssetPrecision TEXT,
    contractType TEXT,
    deliveryDate TEXT,
    filters TEXT,
    filters_dict TEXT,
    liquidationFee TEXT,
    maintMarginPercent TEXT,
    marginAsset TEXT,
    marketTakeBound TEXT,
    maxMoveOrderLimit TEXT,
    onboardDate TEXT,
    orderTypes TEXT,
    pair TEXT,
    permissionSets TEXT,
    pricePrecision TEXT,
    quantityPrecision TEXT,
    quoteAsset TEXT,
    quotePrecision TEXT,
    requiredMarginPercent TEXT,
    status TEXT,
    symbol TEXT UNIQUE NOT NULL,
    timeInForce TEXT,
    triggerProtect TEXT,
    underlyingSubType TEXT,
    underlyingType TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_binance_perpetual_symbol ON binance_perpetual(symbol);

-- XT 永续合约表
CREATE TABLE IF NOT EXISTS xt_perpetual (
    id SERIAL PRIMARY KEY,
    api_id TEXT,
    baseCoin TEXT,
    baseCoinDisplayPrecision TEXT,
    baseCoinPrecision TEXT,
    cnDesc TEXT,
    cnName TEXT,
    cnRemark TEXT,
    contractSize TEXT,
    contractType TEXT,
    curMaxLeverage TEXT,
    deliveryCompletion TEXT,
    deliveryDate TEXT,
    deliveryPrice TEXT,
    depthPrecisionMerge TEXT,
    displaySwitch TEXT,
    enDesc TEXT,
    enName TEXT,
    enRemark TEXT,
    fastTrackCallbackRate1 TEXT,
    fastTrackCallbackRate2 TEXT,
    initLeverage TEXT,
    initPositionType TEXT,
    isDisplay TEXT,
    isOpenApi TEXT,
    labels TEXT,
    latestPriceDeviation TEXT,
    liquidationFee TEXT,
    makerFee TEXT,
    marketCloseTakeBound TEXT,
    marketOpenTakeBound TEXT,
    marketTakeBound TEXT,
    maxEntrusts TEXT,
    maxNotional TEXT,
    maxOpenOrders TEXT,
    maxPrice TEXT,
    maxTrackCallbackRate TEXT,
    minNotional TEXT,
    minPrice TEXT,
    minQty TEXT,
    minStepPrice TEXT,
    minTrackCallbackRate TEXT,
    multiplierDown TEXT,
    multiplierUp TEXT,
    nextOpenTime TEXT,
    offTime TEXT,
    onboardDate TEXT,
    openSwitch TEXT,
    pair TEXT,
    plates TEXT,
    predictEventParam TEXT,
    predictEventSort TEXT,
    predictEventType TEXT,
    pricePrecision TEXT,
    productType TEXT,
    quantityPrecision TEXT,
    quoteCoin TEXT,
    quoteCoinDisplayPrecision TEXT,
    quoteCoinPrecision TEXT,
    riskExpireTime TEXT,
    riskNominalValueCoefficient TEXT,
    spotCoin TEXT,
    state TEXT,
    supportEntrustType TEXT,
    supportOrderType TEXT,
    supportPositionType TEXT,
    supportTimeInForce TEXT,
    symbol TEXT UNIQUE NOT NULL,
    symbolGroupId TEXT,
    symbolId TEXT,
    takerFee TEXT,
    thanosSwitch TEXT,
    tradeSwitch TEXT,
    underlyingType TEXT,
    updatedTime TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_xt_perpetual_symbol ON xt_perpetual(symbol);

-- OKX 永续合约表
CREATE TABLE IF NOT EXISTS okx_perpetual (
    id SERIAL PRIMARY KEY,
    alias TEXT,
    auctionEndTime TEXT,
    baseCcy TEXT,
    category TEXT,
    contTdSwTime TEXT,
    ctMult TEXT,
    ctType TEXT,
    ctVal TEXT,
    ctValCcy TEXT,
    expTime TEXT,
    futureSettlement TEXT,
    groupId TEXT,
    instFamily TEXT,
    instId TEXT UNIQUE NOT NULL,
    instIdCode TEXT,
    instType TEXT,
    lever TEXT,
    listTime TEXT,
    longPosRemainingQuota TEXT,
    lotSz TEXT,
    maxIcebergSz TEXT,
    maxLmtAmt TEXT,
    maxLmtSz TEXT,
    maxMktAmt TEXT,
    maxMktSz TEXT,
    maxPlatOILmt TEXT,
    maxStopSz TEXT,
    maxTriggerSz TEXT,
    maxTwapSz TEXT,
    minSz TEXT,
    openType TEXT,
    optType TEXT,
    posLmtAmt TEXT,
    posLmtPct TEXT,
    preMktSwTime TEXT,
    quoteCcy TEXT,
    ruleType TEXT,
    settleCcy TEXT,
    shortPosRemainingQuota TEXT,
    state TEXT,
    stk TEXT,
    tickSz TEXT,
    tradeQuoteCcyList TEXT,
    uly TEXT,
    upcChg TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_okx_perpetual_instId ON okx_perpetual(instId);

-- BYBIT 永续合约表
CREATE TABLE IF NOT EXISTS bybit_perpetual (
    id SERIAL PRIMARY KEY,
    baseCoin TEXT,
    contractType TEXT,
    copyTrading TEXT,
    deliveryFeeRate TEXT,
    deliveryTime TEXT,
    displayName TEXT,
    forbidUplWithdrawal TEXT,
    fundingInterval TEXT,
    isPreListing TEXT,
    launchTime TEXT,
    leverageFilter TEXT,
    lotSizeFilter TEXT,
    lowerFundingRate TEXT,
    preListingInfo TEXT,
    priceFilter TEXT,
    priceScale TEXT,
    quoteCoin TEXT,
    riskParameters TEXT,
    settleCoin TEXT,
    status TEXT,
    symbol TEXT UNIQUE NOT NULL,
    symbolType TEXT,
    unifiedMarginTrade TEXT,
    upperFundingRate TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_bybit_perpetual_symbol ON bybit_perpetual(symbol);

-- GATE 永续合约表
CREATE TABLE IF NOT EXISTS gate_perpetual (
    id SERIAL PRIMARY KEY,
    config_change_time TEXT,
    create_time TEXT,
    cross_leverage_default TEXT,
    delisted_time TEXT,
    delisting_time TEXT,
    enable_bonus TEXT,
    enable_circuit_breaker TEXT,
    enable_credit TEXT,
    funding_cap_ratio TEXT,
    funding_impact_value TEXT,
    funding_interval TEXT,
    funding_next_apply TEXT,
    funding_offset TEXT,
    funding_rate TEXT,
    funding_rate_indicative TEXT,
    funding_rate_limit TEXT,
    in_delisting TEXT,
    index_price TEXT,
    interest_rate TEXT,
    is_pre_market TEXT,
    last_price TEXT,
    launch_time TEXT,
    leverage_max TEXT,
    leverage_min TEXT,
    long_users TEXT,
    maintenance_rate TEXT,
    maker_fee_rate TEXT,
    mark_price TEXT,
    mark_price_round TEXT,
    mark_type TEXT,
    market_order_size_max TEXT,
    market_order_slip_ratio TEXT,
    name TEXT UNIQUE NOT NULL,
    order_price_deviate TEXT,
    order_price_round TEXT,
    order_size_max TEXT,
    order_size_min TEXT,
    orderbook_id TEXT,
    orders_limit TEXT,
    position_size TEXT,
    quanto_multiplier TEXT,
    ref_discount_rate TEXT,
    ref_rebate_rate TEXT,
    risk_limit_base TEXT,
    risk_limit_max TEXT,
    risk_limit_step TEXT,
    short_users TEXT,
    status TEXT,
    taker_fee_rate TEXT,
    trade_id TEXT,
    trade_size TEXT,
    type TEXT,
    voucher_leverage TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_gate_perpetual_name ON gate_perpetual(name);

-- KUCOIN 永续合约表
CREATE TABLE IF NOT EXISTS kucoin_perpetual (
    id SERIAL PRIMARY KEY,
    adjustActiveTime TEXT,
    adjustK TEXT,
    adjustM TEXT,
    adjustMmrLevConstant TEXT,
    baseCurrency TEXT,
    buyLimit TEXT,
    crossRiskLimit TEXT,
    currentFundingRateGranularity TEXT,
    dailyInterestRate TEXT,
    displayBaseCurrency TEXT,
    displaySymbol TEXT,
    effectiveFundingRateCycleStartTime TEXT,
    expireDate TEXT,
    f TEXT,
    fairMethod TEXT,
    firstOpenDate TEXT,
    fundingBaseSymbol TEXT,
    fundingBaseSymbol1M TEXT,
    fundingFeeRate TEXT,
    fundingQuoteSymbol TEXT,
    fundingQuoteSymbol1M TEXT,
    fundingRateCap TEXT,
    fundingRateFloor TEXT,
    fundingRateGranularity TEXT,
    fundingRateSymbol TEXT,
    highPrice TEXT,
    indexPrice TEXT,
    indexPriceTickSize TEXT,
    indexSymbol TEXT,
    initialMargin TEXT,
    isDeleverage TEXT,
    isInverse TEXT,
    isQuanto TEXT,
    k TEXT,
    lastTradePrice TEXT,
    lotSize TEXT,
    lowPrice TEXT,
    m TEXT,
    maintainMargin TEXT,
    makerFeeRate TEXT,
    makerFixFee TEXT,
    markMethod TEXT,
    markPrice TEXT,
    marketMaxOrderQty TEXT,
    marketStage TEXT,
    maxLeverage TEXT,
    maxOrderQty TEXT,
    maxPrice TEXT,
    maxRiskLimit TEXT,
    minRiskLimit TEXT,
    mmrLevConstant TEXT,
    mmrLimit TEXT,
    multiplier TEXT,
    nextFundingRateDateTime TEXT,
    nextFundingRateTime TEXT,
    openInterest TEXT,
    orderPriceRange TEXT,
    period TEXT,
    preMarketToPerpDate TEXT,
    predictedFundingFeeRate TEXT,
    premiumsSymbol1M TEXT,
    premiumsSymbol8H TEXT,
    priceChg TEXT,
    priceChgPct TEXT,
    quoteCurrency TEXT,
    riskStep TEXT,
    rootSymbol TEXT,
    sellLimit TEXT,
    settleCurrency TEXT,
    settleDate TEXT,
    settlementFee TEXT,
    settlementSymbol TEXT,
    sourceExchanges TEXT,
    status TEXT,
    supportCross TEXT,
    symbol TEXT UNIQUE NOT NULL,
    takerFeeRate TEXT,
    takerFixFee TEXT,
    tickSize TEXT,
    turnoverOf24h TEXT,
    type TEXT,
    volumeOf24h TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_kucoin_perpetual_symbol ON kucoin_perpetual(symbol);

-- MEXC 永续合约表
CREATE TABLE IF NOT EXISTS mexc_perpetual (
    id SERIAL PRIMARY KEY,
    amountScale TEXT,
    apiAllowed TEXT,
    api_id TEXT,
    appraisal TEXT,
    askLimitPriceRate TEXT,
    automaticDelivery TEXT,
    baseCoin TEXT,
    baseCoinIconUrl TEXT,
    baseCoinId TEXT,
    baseCoinName TEXT,
    bidLimitPriceRate TEXT,
    conceptPlate TEXT,
    conceptPlateId TEXT,
    contractSize TEXT,
    countryConfigContractMaxLeverage TEXT,
    createTime TEXT,
    deliveryPriceTrend TEXT,
    deliveryTime TEXT,
    depthStepList TEXT,
    displayName TEXT,
    displayNameEn TEXT,
    feeRateMode TEXT,
    futureType TEXT,
    indexOrigin TEXT,
    initialMarginRate TEXT,
    isHidden TEXT,
    isHot TEXT,
    isMaxLeverage TEXT,
    isNew TEXT,
    isZeroFeeRate TEXT,
    isZeroFeeSymbol TEXT,
    leverageFeeRates TEXT,
    limitMaxVol TEXT,
    liquidationFeeRate TEXT,
    maintenanceMarginRate TEXT,
    makerFeeRate TEXT,
    marketOrderMaxLevel TEXT,
    marketOrderPriceLimitRate1 TEXT,
    marketOrderPriceLimitRate2 TEXT,
    maxLeverage TEXT,
    maxNumOrders TEXT,
    maxVol TEXT,
    minLeverage TEXT,
    minVol TEXT,
    openingCountdownOption TEXT,
    openingTime TEXT,
    positionOpenType TEXT,
    preMarket TEXT,
    priceCoefficientVariation TEXT,
    priceScale TEXT,
    priceUnit TEXT,
    quoteCoin TEXT,
    quoteCoinName TEXT,
    riskBaseVol TEXT,
    riskIncrImr TEXT,
    riskIncrMmr TEXT,
    riskIncrVol TEXT,
    riskLevelLimit TEXT,
    riskLimitCustom TEXT,
    riskLimitMode TEXT,
    riskLimitType TEXT,
    riskLongShortSwitch TEXT,
    settleCoin TEXT,
    showAppraisalCountdown TEXT,
    showBeforeOpen TEXT,
    state TEXT,
    stopOnlyFair TEXT,
    symbol TEXT UNIQUE NOT NULL,
    takerFeeRate TEXT,
    threshold TEXT,
    tieredFeeRates TEXT,
    triggerProtect TEXT,
    type TEXT,
    vid TEXT,
    volScale TEXT,
    volUnit TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_mexc_perpetual_symbol ON mexc_perpetual(symbol);